[workspace]
authors = ["Srikrishna Sekhar <ssekhar@nrao.edu>"]
channels = ["conda-forge"]
name = "blacklight"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pyarrow = ">=23.0.0,<24"
dask = "*"
datashader = "*"
holoviews = "*"
panel = "*"
colorcet = "*"
